const FETCH_USERS = 'FETCH_USERS'
const USERS_FETCH_PROGRESS = 'USERS_FETCH_PROGRESS'
const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS'
const USERS_FETCH_FAILURE = 'USERS_FETCH_FAILURE'

module.exports = {
	FETCH_USERS: FETCH_USERS,
	USERS_FETCH_PROGRESS: USERS_FETCH_PROGRESS,
	USERS_FETCH_SUCCESS: USERS_FETCH_SUCCESS,
	USERS_FETCH_FAILURE: USERS_FETCH_FAILURE,	
}
